# Generated by Django 2.0.6 on 2018-06-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.CharField(max_length=20, null=True)),
                ('director', models.CharField(max_length=40, null=True)),
                ('genre', models.CharField(max_length=50, null=True)),
                ('imdb_score', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('add', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
        ),
    ]
