# Generated by Django 2.0.6 on 2018-06-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movinfo', '0003_remove_movies_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='status',
        ),
    ]
