# Generated by Django 2.0.6 on 2018-06-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movinfo', '0004_remove_movies_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='add',
            new_name='dt_added',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='update',
            new_name='dt_updated',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='imdb_score',
            new_name='movielist_score',
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='popularity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
