# Generated by Django 2.0.6 on 2018-06-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movinfo', '0005_auto_20180618_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='movielist_score',
            new_name='imdb_score',
        ),
    ]
